apiVersion: apps/v1
kind: Deployment
metadata:
  name: final-web-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-brand
  template:
    metadata:
      labels:
        app: my-brand
    spec:
      containers:
      - name: nginx-container
        image: nginx:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: final-service
spec:
  type: NodePort
  selector:
    app: my-brand
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30007
