apiVersion: apps/v1
kind: Deployment
metadata:
  name: recreate-test
spec:
  replicas: 4
  strategy:
    type: Recreate   # <--- Ye hai main cheez
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: web-container
        image: nginx:1.14.2  # Purana version
